server:
  port: 9192

spring:
  zipkin:
    enabled: true
    service:
      name: pay-service
    base-url: http://localhost:9411/
  sleuth:
    enabled: true
    sampler:
      probability: 1
  h2:
    console:
      enabled: true
  application:
    name: PAYMENT-SERVICE

logging:
  file: /Users/utsa/IdeaProjects/logs/microservice.log